// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MigrationTesting.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Migration tests", Description="\tIn order to test the Dynamics database schema\r\n\tAs a user with access to the Dyn" +
        "amics database\r\n\tI want to confirm the schema as defined in document TBC.", SourceFile="Features\\MigrationTests.feature", SourceLine=0)]
    public partial class MigrationTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "MigrationTests.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Migration tests", "\tIn order to test the Dynamics database schema\r\n\tAs a user with access to the Dyn" +
                    "amics database\r\n\tI want to confirm the schema as defined in document TBC.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
 testRunner.Given("there is a connection to the Dynamics database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verify the schema of the Customer table", new string[] {
                "schema"}, SourceLine=11)]
        public virtual void VerifyTheSchemaOfTheCustomerTable()
        {
            string[] tagsOfScenario = new string[] {
                    "schema"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify the schema of the Customer table", null, tagsOfScenario, argumentsOfScenario);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 13
 testRunner.Given("the Customer table exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "TABLE_NAME",
                            "COLUMN_NAME",
                            "DATA_TYPE",
                            "IS_NULLABLE",
                            "CHARACTER_MAXIMUM_LENGTH"});
                table1.AddRow(new string[] {
                            "Customer",
                            "CustomerID",
                            "int",
                            "NO",
                            ""});
                table1.AddRow(new string[] {
                            "Customer",
                            "firstname",
                            "varchar",
                            "YES",
                            "255"});
                table1.AddRow(new string[] {
                            "Customer",
                            "lastname",
                            "varchar",
                            "YES",
                            "255"});
                table1.AddRow(new string[] {
                            "Customer",
                            "birthdate",
                            "varchar",
                            "YES",
                            "255"});
                table1.AddRow(new string[] {
                            "Customer",
                            "city",
                            "varchar",
                            "YES",
                            "255"});
#line 14
 testRunner.Then("verify the schema of the Customer table", ((string)(null)), table1, "Then ");
#line hidden
#line 21
 testRunner.And("verify the Customer record count is 100", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verify the schema of the Address table", new string[] {
                "schema"}, SourceLine=24)]
        public virtual void VerifyTheSchemaOfTheAddressTable()
        {
            string[] tagsOfScenario = new string[] {
                    "schema"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify the schema of the Address table", null, tagsOfScenario, argumentsOfScenario);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 26
 testRunner.Given("the Address table exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "TABLE_NAME",
                            "COLUMN_NAME",
                            "DATA_TYPE",
                            "IS_NULLABLE",
                            "CHARACTER_MAXIMUM_LENGTH"});
                table2.AddRow(new string[] {
                            "Address",
                            "AddressID",
                            "int",
                            "NO",
                            ""});
                table2.AddRow(new string[] {
                            "Address",
                            "AddressLine1",
                            "varchar",
                            "YES",
                            "255"});
                table2.AddRow(new string[] {
                            "Address",
                            "AddressLine2",
                            "varchar",
                            "YES",
                            "255"});
                table2.AddRow(new string[] {
                            "Address",
                            "City",
                            "varchar",
                            "YES",
                            "255"});
                table2.AddRow(new string[] {
                            "Address",
                            "Postcode",
                            "varchar",
                            "YES",
                            "10"});
#line 27
 testRunner.Then("verify the schema of the Address table", ((string)(null)), table2, "Then ");
#line hidden
#line 34
 testRunner.And("verify the Address record count is 80", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
